---
- hosts: all
  become: True
  tasks:
    - name: Install python pip
      yum:
       name: python-pip
       state: present
    - name: install  python module
      pip:
         name: docker-py
         state: present
    - name: start the container
      docker_container:
         name:dock-ansi2
         image:"praneetha22/doc-ansi2:v1.1"
         state:started
